### ISSUE TITLE
Events - Roman thermal cure

### ISSUE THREAD

**Issue by alltheatreides** [alltheatreides/AVE_MARIA_CK3#13]
**BASIC INFO**
- Event for the Roman Basileus or any Ruler living near province 5570 (c_crius) triggered by a Decision
- Trigger: character with Poor health or below.
- Short Event description: therms of pythia are renowned, maybe I should go there and it will make me good

**EVENT 1**
- Option A: Yes go there (AI character personality weighting) - triggers next event after a few days
- Option B: No, let's go to Prusa instead (flavour change, nothing much different bonus wise) - triggers next event after a few days
 - Option C: No, I am doomed (AI character personality weighting) - Nothing
 
**EVENT 2**
- Desc: Everyone ready for the trip, description of a byzantine/roman bath from the period, feels good
- Option: Small Health Bonus, higher if lung disease

@Conchodebar
@Maneege

**Comment by Conchodebar** [comment]
I'll start working on this now, unless someone else has already started
