### ISSUE TITLE
Administrative Proposal

### ISSUE THREAD

**Issue by gluff95** [alltheatreides/AVE_MARIA_CK3#2]
To better reflect the reality of mid-to-late eleventh century Byzantine administration, I propose a change to the existing systems in place. Also, it should help simplify the system of administration and give the player the ability to control their regions better.

## Types of Administrative District

Instead of having two overlapping systems of administrative and military officials each controlling land, we should allow the land to be designated as a particular type of region via the feudal contract menu, which will affect the title of the 'vassal' and their role in the political system, as well as the available laws. These duchy-level delineations are:

### Stratified Theme
- Run by a strategos
- Primarily produces soldiers and a bit of tax (and if it is made possible in the future, crops/supplies/military resources)
- County level divisions are tourma, under a tourmarches (I've changed the 'knight' title to the more correct 'topoteretes')
- Strategoi were not given command of tagmatic troops, so they only get to command their levies.

### Fiscalised Theme
- Run by a krites
- Primarily produces tax and additional MaA capacity
- All themes, no matter how fiscalised, provided an amount of soldiers, but by the eleventh century these soldiers were of poor quality.
- Obviously, since krites are civilians they can't lead soldiers themselves, but should we bother with assigning the soldiers these themes provide to a strategos (the way it is now), or do we 'add them' (I'm not sure if this possible) to another officer's command? Any strategos of a fiscalised theme is going to be almost useless as a military leader and politically trivial (too junior to ever consider a bid for the throne, and not enough clout to try to climb the ranks either).

### Doukaton
- Run by a doux, who has significantly more authority than either a strategos or a krites
- More balanced province that lots of soldiers and a bit of tax
- They can only exist in frontier regions (must be bordering a neighbouring power or be bordering another region of the empire that does)
- The doukes are also senior commanders and often had tagmata under their direct control (Antioch was HQ for some tagmata regiments). This makes them some of the most dangerous rivals to the emperor politically, balancing out the usefulness of a doukaton over a thema.

### Kouratoreia
- A kouratoreia is an imperial estate which were often established in conquered lands in order to prevent the great landowning families from acquiring even more power by purchasing the newly available land and leasing it out.
- Run by a kourator, a direct appointee of the emperor with zero involvement in the political system. Essentially a private bureaucrat.
- Produces no soldiers at all, but lots of tax.
- Should probably have a cap on these things, money with no consequences.

### Proposed Late Byzantine district types, to be added later
- Despotate, under a despot
- Kephalatikion, under a kephale

## How it Works
In the 1066 bookmark, pretty much all of the themata start as Fiscalised Themata, with the following exceptions:

- Kappadokia: Stratified Theme
- Sebasteia: Stratified Theme
- Khaldia: Stratified Theme
- Anatolikon: Stratified Theme
- Mesopotamia: Doukaton
- Vaspurakan: Doukaton
- Antioch: Doukaton
- Greater Armenia (Should be either 'Ani' or 'Iberia', the Byzantine stopped referring to Armenia as such in the 7th century): Doukaton
- Moesia (should be renamed to Paristrion): Doukaton

The types of theme grant access to a different slider which can be increased or decreased with political consequences. For example, increasing a slider in a Stratified Theme increases the troop levy, but also makes the emperor less popular. I've yet to fully conceptualise how this will work in detail, but that information is coming I promise.

I am also thinking of adding inertia to this system to make it interesting - fiscalised themes drift towards stagnation, the minimum number of troops a stratified theme provides is slowly decreased etc. The sliders unique to each type shift over time by themselves, and it is up to the player to keep them in the right place for their needs.

**Comment by alltheatreides** [comment]
Regarding Kouratoreia:

> Should probably have a cap on these things, money with no consequences.

Some form of soft cap could be an event if you have too many of this type of contract similar to the pesky CK2 event of relatives asking you to give them land.
So an event prompting you to give up the land and with a hefty Popularity penalty associated to it.

**Comment by gluff95** [comment]
> Some form of soft cap could be an event if you have too many of this type of contract similar to the pesky CK2 event of relatives asking you to give them land.
> So an event prompting you to give up the land and with a hefty Popularity penalty associated to it.
Good idea - the kouratoreia were set up to prevent the _dynatoi_ (powerful landowning families such as the Phokades and the Doukai) from claiming it, so I'm thinking something like this:

- If the emperor has too much land designated as kouratoreia, a request comes from an (unlanded?) senator to allow him to purchase the estates.
- A player with a decent diplomacy skill can negotiate terms to be more favourable (can choose how the land
- If the emperor agrees to the request, the kourator is dismissed and the land becomes a theme run by the person who made the request. The emperor gets a hefty Popularity penalty.
- If the emperor refuses the request, the senator and the family of the senator who made the request are very unhappy and this opinion shift might have political consequences (needs a bit more thought). I also thought about ticking down the emperor's Legitimacy by a small amount to represent that the aristocracy think them to be a money-grubbing miser.
- Potentially, a nuanced corruption mechanic could be added in future which would be influenced by choices here too.

**Comment by IhateTrains** [comment]
I've found a pretty detailed map of Roman administration in 1050:
![mainmap](https://teamweb.uni-mainz.de/fb07/maps_project/Freely%20Available%20Maps/HALDON,%20The%20Palgrave%20Atlas%20of%20Byzantine%20History.%20Basingstoke%202005/37.%20Themata%20and%20ducates,%201050.jpg)

Map 6.3 with the rest of the legend is here:
![map6.3](https://teamweb.uni-mainz.de/fb07/maps_project/Freely%20Available%20Maps/HALDON,%20The%20Palgrave%20Atlas%20of%20Byzantine%20History.%20Basingstoke%202005/36.%20Themata,%20920.jpg)
Other similar maps (all for 1045):
![map1](https://i.imgur.com/JQxxPqr.jpg)
![map2](https://upload.wikimedia.org/wikipedia/commons/f/fa/Map_Byzantine_Empire_1045.svg)
![map3](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/264498ee-73ce-49d8-8ebc-f1f845fff514/d97vjvb-86f71ae0-b597-4599-8331-3fea9f99289c.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI2NDQ5OGVlLTczY2UtNDlkOC04ZWJjLWYxZjg0NWZmZjUxNFwvZDk3dmp2Yi04NmY3MWFlMC1iNTk3LTQ1OTktODMzMS0zZmVhOWY5OTI4OWMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.PGZuHLYLGtiT5zV8IUYgFEpHv7ToLYSQRHZE7udrb6o)

**Comment by gluff95** [comment]
Still to do on this:

- [ ] Fix the "Obligation Invalidated" spam when starting a new game.
- [ ] Tweak numbers and balance
- [ ] Add scripted triggers and script values to the contract window
- [ ] Add event/scripted effect to properly handle a government change via a contract
- [ ] Investigate the possibility of a new GUI to replace the 'Feudal Contract' window with our own 'Imperial Obligations' window @alltheatreides (duplicate the feudal contract GUI and modify the copy + create a new interaction that uses the new window maybe?)

**Comment by gluff95** [comment]
Next planning step, contracts for county and kingdom-level vassals.
#### Turma - County-tier territory
- Run by a tourmarches
- Basic tax and levy slider
- Special contract type "Kleisoura", which essentially fortifies the province.

#### Katepanikion - Kingdom-tier territory
- Run by a katepano
- Basic tax slider
- Katepanikion unique slider for militarisation/fiscalisation
