### ISSUE TITLE
Geographical Changes

### ISSUE THREAD

**Issue by gluff95** [alltheatreides/AVE_MARIA_CK3#3]
Use this to track all geographical/map changes that are proposed. Either edit the post or add new comments, using the todo list function to ensure we keep track.

### Thrace, Macedonia and Bulgaria
In vanilla CK3, they've made this region look like it did post-1204 - some of these duchies did not exist yet, and others that did are missing.

#### Sirmiou
- [x] For the Byzantines, merge the Duchies of Macva and Vidin to create the duchy-level province of Sirmiou.

#### Philippopolis
Divide into three parts:
- [x] Add the counties of Adrianopolis, Janitsa, Mezeshka, Didmyoteichon, Lyutitsa, Byalgrad, Ustra and Zherkovo to the new duchy-level province of Macedonia.
- [x] Add Sozopolis to Thrace
- [x] Add the remaining provinces to Moesia, which should be renamed Paristrion (yes, this makes former Moesia enormous, but if it becomes a problem we can split this mega-duchy into two part, Paradounavon and Paristrion).

#### Strymon
- [x] Remove the counties of Mosynopolis and Traianopolis from Strymon and add them to Macedonia

**Comment by IhateTrains** [comment]
> Remove the counties of Mosynopolis and Traianopolis from Strymon and add them to Macedonia

May I ask about the source for this? On this map for 1045 AD Traianopolis is in Strymonos:https://camo.githubusercontent.com/e55c009f1f005e35ad66b2c4a725315b35dd6328a6b5c687ec308524bc45d824/68747470733a2f2f692e696d6775722e636f6d2f4a5178785071722e6a7067
