### ISSUE TITLE
Gregorian Reform - Bishop Landed Titles

### ISSUE THREAD

**Issue by alltheatreides** [alltheatreides/AVE_MARIA_CK3#5]
### Landed Titles

Add County tier Bishoprics landed titles.

Add Duchy tier Archbishoprics landed titles.

All titles should be added in common/landed_titles/ave_maria_christian_flavour_landed_titles.txt and according to the relevant model.

[Reference Map](http://www.menestrel.fr/IMG/jpg/Eur1100-2.jpg). (Date is for 1100 but we will go with it)
[Reference Website](http://www.menestrel.fr/?Bishoprics-and-archbishoprics-Europe&lang=en).

### Landed Titles History

Put the newly created history in history/titles/ave_maria_bishop_titles.txt following the relevant model.

**Comment by Grallak123** [comment]
[bishops.txt](https://github.com/alltheatreides/AVE_MARIA_CK3/files/5568021/bishops.txt)

**Comment by Grallak123** [comment]
[bishops.txt](https://github.com/alltheatreides/AVE_MARIA_CK3/files/5568093/bishops.txt)
fixed some stuff 1

**Comment by Grallak123** [comment]
[archbishops.txt](https://github.com/alltheatreides/AVE_MARIA_CK3/files/5568152/archbishops.txt)
fixed some stuff 2

**Comment by Grallak123** [comment]
[bishops.txt](https://github.com/alltheatreides/AVE_MARIA_CK3/files/5568859/bishops.txt)
italy, corsica, sardinia, sicily still remaining

**Comment by Grallak123** [comment]
[archbishops.txt](https://github.com/alltheatreides/AVE_MARIA_CK3/files/5574576/archbishops.txt)
[bishops.txt](https://github.com/alltheatreides/AVE_MARIA_CK3/files/5574577/bishops.txt)
done
